EXPERIMENT:
  NAME: "byol_pretext"
  TAG: "baselines"
  PROJECT: "baseline project"
  DEBUG: False
  REPETITION_NUM: 3 # Number of repetition times
  TASK: "pretext"
  LOG_IMAGES: False
  RESUME: False # Resume training
  CHECKPOINT: "" # 'Log_2020-03-19_19-53-27'
  CHKP_IDX: None # Choose index of checkpoint to start from. If None, uses the latest chkp
  SEED: 42
  CHECKPOINT_GAP: 10
  KNN: True
  EVAL_ONLY: False
  EVAL_NEXT: True
  EVAL_LINEAR: False
  EVAL_SEMI: True
  PRETRAINED_PATH: "/home/song/code/current/meg_classification/ssl/results/baseline project/byol_pretext_2024-07-10_08-30-02"
DATASET:
  ROOT: "/home/song/datasets/EEG"
  TYPE: "deap"
  CHANNELS: 32
  POINTS: 128
  NUM_CLASSES: 2
  TEST:
    BATCH_SIZE: 128
MODEL:
  TYPE: "BYOL"
  ARGS:
    BACKBONE: "varcnn"
    SIAMESE: True
    USE_MOMENTUM: False # True for BYOL, False for SimSiam
    PROJECTION_DIM: 128
    HIDDEN_LAYER: -1
    PROJECTION_HIDDEN_SIZE: 4096
    TAU_BASE: 0.996
    N_FEATURES: 11520
    WARMUP_EPOCHS: -1
    REC_WEIGHT: 1
    CLS_WEIGHT: 0.1
    PRED_WEIGHT: 0.1
    SOURCE_CHANNELS: 180
  CRITERION:
    TYPE:
      "RegressionLoss"
      # SOURCE_CHANNELS: 36
SOLVER:
  TRAINER: "BYOL"
  BATCH_SIZE: 512
  EPOCHS: 10
  LR: 0.01
  SCHEDULER:
    TYPE: "ExponentialLR"
    GAMMA: 0.9
    MIN_LR: 0.0001
EVAL_LINEAR:
  CLASSIFIER: "LinearClassifier"
  BATCH_SIZE: 512
  EPOCHS: 200
  LR: 0.5
  CRITERION: "CE"
  SCHEDULER:
    TYPE: "ExponentialLR"
    GAMMA: 0.99
    MIN_LR: 0.001
EVAL_SEMI:
  DATA_PATH: "/home/song/datasets/EEG/deap/semi_train"
