EXPERIMENT:
  NAME: "byol_pretext"
  TAG: "baselines"
  PROJECT: "baseline project"
  DEBUG: False
  REPETITION_NUM: 3 # Number of repetition times
  TASK: "pretext"
  RESUME : False  # Resume training
  CHECKPOINT : "" # 'Log_2020-03-19_19-53-27'
  CHKP_IDX : None  # Choose index of checkpoint to start from. If None, uses the latest chkp
  SEED: 42
  CHECKPOINT_GAP: 10
  KNN: True
  EVAL_ONLY: True
  EVAL_NEXT: True
  EVAL_LINEAR: False
  EVAL_SEMI: True
  PRETRAINED_PATH: "/home/song/code/current/meg_classification/ssl/results/baseline project/byol_pretext_2024-07-17_02-01-14"
DATASET:
  ROOT: "/home/song/datasets/MEG"
  TYPE: "DecMeg"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
  TEST:
    BATCH_SIZE: 128
MODEL:
  TYPE: "BYOL"
  ARGS:
    BACKBONE: "varcnn"
    SIAMESE: True
    USE_MOMENTUM: False # True for BYOL, False for SimSiam
    PROJECTION_DIM: 512
    N_FEATURES: 22500
    PROJECTION_HIDDEN_SIZE: 4096
    HIDDEN_LAYER: -1
    TAU_BASE: 0.996
    SOURCE_CHANNELS: 180
  CRITERION:
    TYPE: "RegressionLoss"
      # SOURCE_CHANNELS: 36
SOLVER:
  TRAINER: "BYOL"
  BATCH_SIZE: 512
  EPOCHS: 10
  LR: 0.005
  SCHEDULER:
    TYPE: "ExponentialLR"
    GAMMA: 0.99
    MIN_LR: 0.0001
EVAL_LINEAR:
  CLASSIFIER: "LinearClassifier"
  BATCH_SIZE: 512
  EPOCHS: 200
  LR: 0.5
  CRITERION: "CE"
  SCHEDULER:
    TYPE: "ExponentialLR"
    GAMMA: 0.99
    MIN_LR: 0.001
EVAL_SEMI:
  DATA_PATH: "/home/song/datasets/MEG/DecMeg/semi_train"

