EXPERIMENT:
  NAME: "simclr"
  TAG: "baselines"
  PROJECT: "base project"
  DEBUG: True
  REPETITION_NUM: 5 # Number of repetition times
  TASK: "pretext"
DATASET:
  TYPE: "HAR"
  CHANNELS: 9
  POINTS: 128
  NUM_CLASSES: 6
  TEST:
    BATCH_SIZE: 128
MODEL:
  TYPE: "SimCLR"
  ARGS:
    MAX_POOL: 2
    DROP_OUT: 0.5
    # SOURCE_CHANNELS: 36
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 100
  LR: 0.0003
