EXPERIMENT:
  NAME: "simclr"
  TAG: "baselines"
  PROJECT: "debug project"
  DEBUG: True
  REPETITION_NUM: 5 # Number of repetition times
  TASK: "pretext"
DATASET:
  ROOT: "/home/song/datasets/timeseries/"
  TYPE: "HAR"
  CHANNELS: 9
  POINTS: 128
  NUM_CLASSES: 6
  TEST:
    BATCH_SIZE: 128
MODEL:
  TYPE: "SimCLR"
  ARGS:
    BACKBONE: "resnet50"
    TEMPERATURE: 0.5
    SIAMESE: True
    PROJECTION_DIM: 128
    # SOURCE_CHANNELS: 36
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 100
  LR: 0.0003
