EXPERIMENT:
  NAME: "current_pretext"
  TAG: "proposed"
  PROJECT: "proposed project"
  DEBUG: False 
  LOG_IMAGES: False
  REPETITION_NUM: 1 # Number of repetition times
  TASK: "pretext"
  RESUME : False # Resume training
  CHECKPOINT : "proposed project/current_pretext_2024-05-25_11-14-32" # 'Log_2020-03-19_19-53-27'
  CHKP_IDX : 9  # Choose index of checkpoint to start from. If None, uses the latest chkp
  CHECKPOINT_GAP: 10
DATASET:
  ROOT: "/home/song/datasets/MEG"
  TYPE: "CamCAN"
  CHANNELS: 204
  POINTS: 100
  NUM_CLASSES: 2
  TEST:
    BATCH_SIZE: 128
MODEL:
  TYPE: "CurrentCLR"
  ARGS:
    BACKBONE: "varcnn"
    SIAMESE: True
    USE_MOMENTUM: True  # True for BYOL, False for SimSiam
    HIDDEN_LAYER: -1
    PROJECTION_DIM: 128
    PROJECTION_HIDDEN_SIZE: 4096
    TAU_BASE: 0.996
    WARMUP_EPOCHS: -1
    REC_WEIGHT: 1
    CLS_WEIGHT: 0.1
    PRED_WEIGHT: 0.1
    # SOURCE_CHANNELS: 36
  CRITERION:
    TYPE: "RegressionLoss"
      # SOURCE_CHANNELS: 36
SOLVER:
  TRAINER: "current"
  BATCH_SIZE: 512 
  EPOCHS: 40
  LR: 0.01
  SCHEDULER:
    TYPE: "ExponentialLR"
    GAMMA: 0.95
    MIN_LR: 0.0001

