EXPERIMENT:
  NAME: "InfoTS_Pretrain"
  TAG: "baselines"
  PROJECT: "baseline project"
  DEBUG: False
  REPETITION_NUM: 3 # Number of repetition times
  TASK: "pretext"
  RESUME : False  # Resume training
  CHECKPOINT : "" # 'Log_2020-03-19_19-53-27'
  CHKP_IDX : None  # Choose index of checkpoint to start from. If None, uses the latest chkp
  CHECKPOINT_GAP: 10
  SEED: 42
  KNN: True
  EVAL_ONLY: True
  EVAL_NEXT: True
  EVAL_LINEAR: False
  EVAL_SEMI: True
  PRETRAINED_PATH: "/home/song/code/current/meg_classification/ssl/results/baseline project/InfoTS_Pretrain_2024-07-04_11-20-21"
DATASET:
  ROOT: "/home/song/datasets/EEG"
  TYPE: "sleepedf20"
  CHANNELS: 1
  POINTS: 3000
  NUM_CLASSES: 5
  TEST:
    BATCH_SIZE: 128
MODEL:
  TYPE: "SimCLR"
  ARGS:
    BACKBONE: "eegconvnet"
    TEMPERATURE: 0.5
    SIAMESE: True
    N_FEATURES: 256
    PROJECTION_DIM: 256
    PROJECTION_HIDDEN_SIZE: 2048
    # SOURCE_CHANNELS: 36
  CRITERION:
    TYPE: "NT_Xent"
    ARGS:
      TEMPERATURE: 0.5
      # SOURCE_CHANNELS: 36
SOLVER:
  TRAINER: "InfoTS"
  BATCH_SIZE: 128
  EPOCHS: 10
  META_LR: 0.01
  LR: 0.05
  SCHEDULER:
    TYPE: "ExponentialLR"
    GAMMA: 0.99
    MIN_LR: 0.0001
EVAL_LINEAR:
  CLASSIFIER: "LinearClassifier"
  BATCH_SIZE: 128
  EPOCHS: 200
  LR: 0.5
  CRITERION: "CE"
  SCHEDULER:
    TYPE: "ExponentialLR"
    GAMMA: 0.99
    MIN_LR: 0.001
EVAL_SEMI:
  DATA_PATH: "/home/song/datasets/EEG/sleepedf20/semi_train"
