EXPERIMENT:
  NAME: "current_pretext"
  TAG: "proposed"
  PROJECT: "proposed project"
  DEBUG: False 
  LOG_IMAGES: False
  REPETITION_NUM: 3 # Number of repetition times
  TASK: "pretext"
  RESUME : False # Resume training
  CHECKPOINT : "proposed project/current_pretext_2024-05-25_11-14-32" # 'Log_2020-03-19_19-53-27'
  CHKP_IDX : 9  # Choose index of checkpoint to start from. If None, uses the latest chkp
  CHECKPOINT_GAP: 10
  SEED: 42
  KNN: True
  EVAL_ONLY: True
  EVAL_NEXT: True
  EVAL_LINEAR: True
  EVAL_SEMI: False
  PRETRAINED_PATH: "/home/song/code/current/meg_classification/ssl/results/proposed project/current_pretext_2024-07-21_11-03-55"
DATASET:
  ROOT: "/home/song/datasets/MEG"
  TYPE: "CamCAN"
  CHANNELS: 204
  POINTS: 100
  NUM_CLASSES: 2
  TEST:
    BATCH_SIZE: 128
MODEL:
  TYPE: "CurrentSimCLR"
  ARGS:
    BACKBONE: "varcnn"
    TEMPERATURE: 0.5
    SIAMESE: True
    USE_MOMENTUM: True  # True for BYOL, False for SimSiam
    PROJECTION_DIM: 128
    PROJECTION_HIDDEN_SIZE: 4096
    N_FEATURES: 1800
    SOURCE_CHANNELS: 36
    TAU_BASE: 0.996
    WARMUP_EPOCHS: -1
    REC_WEIGHT: 1
    CLS_WEIGHT: 0.1
    PRED_WEIGHT: 1
  CRITERION:
    TYPE: "NT_Xent"
    ARGS:
      TEMPERATURE: 0.5
      # SOURCE_CHANNELS: 36
SOLVER:
  TRAINER: "currentsimclr"
  BATCH_SIZE: 400
  EPOCHS: 10
  LR: 0.001
  SCHEDULER:
    TYPE: "ExponentialLR"
    GAMMA: 0.9
    MIN_LR: 0.0001
EVAL_LINEAR:
  CLASSIFIER: "LinearClassifier"
  BATCH_SIZE: 512
  EPOCHS: 100
  LR: 0.5
  CRITERION: "CE"
  SCHEDULER:
    TYPE: "ExponentialLR"
    GAMMA: 0.99
    MIN_LR: 0.001
EVAL_SEMI:
  DATA_PATH: "/home/song/datasets/MEG/CamCAN/semi_train"
  SAVE_CKPT: False
