EXPERIMENT:
  NAME: "byol_pretext"
  TAG: "baselines"
  PROJECT: "baseline project"
  DEBUG: False
  REPETITION_NUM: 2 # Number of repetition times
  TASK: "pretext"
  RESUME : False # Resume training
  CHECKPOINT : "" # 'Log_2020-03-19_19-53-27'
  CHKP_IDX : None  # Choose index of checkpoint to start from. If None, uses the latest chkp
  CHECKPOINT_GAP: 1
  SEED: 42
  KNN: True
  EVAL_ONLY: True
  EVAL_NEXT: True
  EVAL_LINEAR: False
  EVAL_SEMI: True
  PRETRAINED_PATH: "/home/song/code/current/meg_classification/ssl/results/baseline project/byol_pretext_2024-07-10_06-55-09"
DATASET:
  ROOT: "/home/song/datasets/EEG"
  TYPE: "sleepedf20"
  CHANNELS: 1
  POINTS: 3000
  NUM_CLASSES: 5
  TEST:
    BATCH_SIZE: 128
MODEL:
  TYPE: "BYOL"
  ARGS:
    BACKBONE: "eegconvnet"
    SIAMESE: True
    USE_MOMENTUM: True # True for BYOL, False for SimSiam
    HIDDEN_LAYER: -1
    PROJECTION_DIM: 256
    N_FEATURES: 256
    PROJECTION_HIDDEN_SIZE: 2048
    TAU_BASE: 0.996
    # SOURCE_CHANNELS: 36
  CRITERION:
    TYPE: "RegressionLoss"
      # SOURCE_CHANNELS: 36
SOLVER:
  TRAINER: "BYOL"
  BATCH_SIZE: 512
  EPOCHS: 1
  LR: 0.0001
  SCHEDULER:
    TYPE: "ExponentialLR"
    GAMMA: 0.9
    MIN_LR: 0.0000001
EVAL_LINEAR:
  CLASSIFIER: "LinearClassifier"
  BATCH_SIZE: 512
  EPOCHS: 2
  LR: 0.5
  CRITERION: "CE"
  SCHEDULER:
    TYPE: "ExponentialLR"
    GAMMA: 0.99
    MIN_LR: 0.001
EVAL_SEMI:
  DATA_PATH: "/home/song/datasets/EEG/sleepedf20/semi_train"

