EXPERIMENT:
  NAME: "tse_linear_eval"
  TAG: "baselines"
  PROJECT: "debug project"
  DEBUG: True 
  REPETITION_NUM: 5 # Number of repetition times
  TASK: "train"
  RESUME : False  # Resume training
  CHECKPOINT : "" # 'Log_2020-03-19_19-53-27'
  CHKP_IDX : None  # Choose index of checkpoint to start from. If None, uses the latest chkp
  KNN: True
  CHECKPOINT_GAP: 100
DATASET:
  ROOT: "/home/song/datasets/EEG"
  TYPE: "sleepedf20"
  CHANNELS: 1
  POINTS: 3000
  NUM_CLASSES: 5
  TEST:
    BATCH_SIZE: 128
MODEL:
  TYPE: "TSEncoder"
  ARGS:
    BACKBONE: "varcnn"
    SIAMESE: True
    TEMPERATURE: 0.5
    PROJECTION_DIM: 512
    DEPTH: 3
    HIDDEN_SIZE: 64
    MASK_MODE: "binomial"
    N_FEATURES: 512 # backbone output feature dimension
    MAX_TRAIN_LENGTH: 3000
    CLASSIFIER: "LinearClassifier"
    PRETRAINED_PATH: "/home/song/code/current/meg_classification/ssl/results/baseline project/tse_pretext_2024-07-03_05-55-50/checkpoints/epoch_9_0_chkp.tar"
    # SOURCE_CHANNELS: 36
  CRITERION:
    TYPE: "CE"
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 200
  LR: 0.5
  SCHEDULER:
    TYPE: "ExponentialLR"
    GAMMA: 0.99
    MIN_LR: 0.001