EXPERIMENT:
  NAME: "tse_pretext"
  TAG: "baselines"
  PROJECT: "baseline project"
  DEBUG: True 
  REPETITION_NUM: 1 # Number of repetition times
  TASK: "pretext"
  RESUME : False  # Resume training
  CHECKPOINT : "" # 'Log_2020-03-19_19-53-27'
  CHKP_IDX : None  # Choose index of checkpoint to start from. If None, uses the latest chkp
  CHECKPOINT_GAP: 10
  SEED: 42
DATASET:
  ROOT: "/home/song/datasets/EEG"
  TYPE: "sleepedf20"
  CHANNELS: 1
  POINTS: 3000
  NUM_CLASSES: 5
  TEST:
    BATCH_SIZE: 128
MODEL:
  TYPE: "TSEncoder"
  ARGS:
    SIAMESE: True
    TEMPERATURE: 0.5
    PROJECTION_DIM: 512
    DEPTH: 3
    HIDDEN_SIZE: 64
    MASK_MODE: "binomial"
    MAX_TRAIN_LENGTH: 3000
  CRITERION:
    TYPE: "InfoNCE"
      # SOURCE_CHANNELS: 36
SOLVER:
  TRAINER: "TSEncoder"
  BATCH_SIZE: 64
  EPOCHS: 10
  LR: 0.001
  SCHEDULER:
    TYPE: "ExponentialLR"
    GAMMA: 0.95
    MIN_LR: 0.0001

