EXPERIMENT:
  NAME: "simclr_linear_eval"
  TAG: "baselines"
  PROJECT: "baseline project"
  DEBUG: True 
  REPETITION_NUM: 5 # Number of repetition times
  TASK: "train"
  RESUME : False  # Resume training
  CHECKPOINT : "" # 'Log_2020-03-19_19-53-27'
  CHKP_IDX : None  # Choose index of checkpoint to start from. If None, uses the latest chkp
DATASET:
  ROOT: "/home/song/datasets/timeseries/"
  TYPE: "HAR"
  CHANNELS: 9
  POINTS: 128
  NUM_CLASSES: 6
  TEST:
    BATCH_SIZE: 128
MODEL:
  TYPE: "SimCLR"
  ARGS:
    BACKBONE: "resnet50"
    TEMPERATURE: 0.5
    SIAMESE: True
    N_FEATURES: 128 # backbone output feature dimension
    PROJECTION_DIM: 128
    CLASSIFIER: "LinearClassifier"

    # SOURCE_CHANNELS: 36
  CRITERION:
    TYPE: "InfoNCE"
    ARGS:
      TEMPERATURE: 0.5
      # SOURCE_CHANNELS: 36
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 400
  LR: 0.05
  SCHEDULER:
    TYPE: "ExponentialLR"
    GAMMA: 0.98
    MIN_LR: 0.0001