EXPERIMENT:
  NAME: "timenet"
  TAG: "setting1"
  PROJECT: "base project"
  DEBUG: True
  REPETITION_NUM: 1 # Number of repetition times
DATASET:
  TYPE: "CamCAN"
  CHANNELS: 204
  POINTS: 100
  NUM_CLASSES: 2
  TEST:
    BATCH_SIZE: 1024
MODEL:
  TYPE: "TimeNet"
  ARGS:
    CHANNEL_1: 32
    CHANNEL_2: 64
    KERNEL_SIZE_1: 7
    KERNEL_SIZE_2: 7
    MAX_POOL: 2
    BATCH_NORM_FLAG: True
SOLVER:
  BATCH_SIZE: 1024
  EPOCHS: 50
  LR: 0.001
